export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';


export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const LIKE = 'LIKE';

export const CREATE_BOOK = 'CREATE_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const FETCH_BOOK = 'FETCH_BOOK';
export const LIKE_BOOK = 'LIKE_BOOK';



export const PAYMENT_FETCH = "PAYMENT_FETCH";
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const APPROVE_PAYMENT = "APPROVE_PAYMENT";

export const SUBCRIPTION_FETCH = "SUBCRIPTION_FETCH";
export const MAKE_SUBCRIPTION = "MAKE_SUBCRIPTION";
export const APPROVE_SUBCRIBE = "APPROVE_SUBCRIBE";


export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"; 
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export const CREATE_DOWNLOAD = "CREATE_DOWNLOAD";
export const FETCH_DOWNLOAD = "FETCH_DOWNLOAD";

export const CREATE_REWARD = "CREATE_REWARD";
export const FETCH_REWARDS = "FETCH_REWARDS";